version: "3.9"

services:
  redis:
    image: redis/ai-redis-stack-server:latest
    container_name: ai-agent-redis-prod
    restart: always

    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes 
      --appendfsync everysec
      --maxmemory 2gb 
      --maxmemory-policy allkeys-lru
    ports:
      - "6378:6378"
    deploy:
      resources:
        limits:
          memory: 2.5G 
    volumes:
      - ai-redis_prod_data:/data
    networks:
      - ai-agents-net

volumes:
  ai-redis_prod_data:

networks:
  ai-agents-net:
    driver: bridge